[project]
name = 'Disaster-Relief-Coordination-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donation-tracking]
path = 'contracts/donation-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.need-assessment]
path = 'contracts/need-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-allocation]
path = 'contracts/resource-allocation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
